version: weights_v1
weights:
    Profile:
        Completeness: 10
        ContentQuality: 10
        Grammar: 0
        Length: 0
        RoleRelevance: 0
        # section_weight: 0.5
    Education:
        Completeness: 10
        ContentQuality: 0
        Grammar: 0
        Length: 0
        RoleRelevance: 10
        # section_weight: 0.5
